<?php

$sql_connection = new mysqli("localhost","root","");

$sql_connection->query("CREATE DATABASE IF NOT EXISTS NEMA_REGISTRY");

$sql_connection->query("CREATE TABLE IF NOT EXISTS districts(ID INT(15) NOT NULL AUTO_INCREMENT, PRIMARY KEY(ID), NAME VARCHAR(30) NOT NULL UNIQUE)");

$sql_connection->query("CREATE TABLE tree_types(ID INT(12) NOT NULL AUTO_INCREMENT, PRIMARY KEY(ID), TYPE_NAME VARCHAR(13) NOT NULL) ");

$string = $sql_connection->query("CREATE TABLE members(ID INT(12) NOT NULL  AUTO_INCREMENT, PRIMARY KEY(ID), NAME VARCHAR(30) NOT NULL, EMAIL VARCHAR(40) NOT NULL, PASSWORD VARCHAR(40) NOT NULL, DISTRICT_ID INT(15) NOT NULL, FOREIGN KEY(DISTRICT_ID) REFERENCES districts(ID))");



